### ISSUE TITLE
How to output flow frames into u/ and v/

### ISSUE THREAD

**Issue by xianyuanliu** [dl-container-registry/furnari-flow#6]
Hi,
I cannot use docker, and thus I use `compute_flow DIR img_%07d.jpg flow_%s_%07d.jpg` to extract the flow frames. However, flow_x_%07.jpg and flow_y_%07.jpg are saved in the same directory. Could you please tell me how to set the arguments to save respectively in u and v directory? Many thanks!

**Comment by willprice** [comment]
There's a wrapper script that calls compute flow and moves the flow files
to a directory, this is what is called from the docker image.
